#!/usr/bin/env python3
"""
fetch_admob.py — Fetch AdMob network performance data (impressions, clicks, earnings)
per app / ad unit and generate an AI-written interpretation of the numbers.

This is a STANDALONE script: it does not depend on fetch_data.py or generate_report.py.
It fetches data, saves a timestamped JSON file to data/, and (unless --fetch-only) queries
an LLM to produce one Markdown report per app.

Usage:
  python3 fetch_admob.py --days 7                          # fetch + LLM report (default)
  python3 fetch_admob.py --days 7 --fetch-only             # only fetch data, save JSON
  python3 fetch_admob.py --file data/admob_20260809_*.json # LLM report from existing JSON
  python3 fetch_admob.py --discover                        # auto-list apps & ad units from API
  python3 fetch_admob.py --ad-units-config admob_ad_units.json  # use declared ad-unit mapping
  python3 fetch_admob.py --local                           # use local LLM instead of Gemini

Requirements:
  - AdMob API enabled in Google Cloud Console
  - OAuth client ID (Desktop app) created in Cloud Console, credentials saved
  - Google Account invited to the AdMob account (Settings > Users) and invite accepted
  - Refresh token generated once via admob_oauth_setup.py, then stored in .env
  - GEMINI_API_KEY in .env for the LLM report step

Auth notes:
  AdMob does NOT support service accounts. It requires user-based OAuth 2.0.
  Configure these env vars (see .env.example):
    ADMOB_CLIENT_CREDENTIALS=<path to oauth client JSON>   (or ADMOB_CLIENT_ID/ADMOB_CLIENT_SECRET)
    ADMOB_REFRESH_TOKEN=<generated by admob_oauth_setup.py>
"""

import os
import json
import argparse
import time
import subprocess
from datetime import datetime, timedelta

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from dotenv import load_dotenv

load_dotenv()

ADMOB_SCOPE = "https://www.googleapis.com/auth/admob.readonly"
# AdMob report API allows a maximum date range per request
MAX_REPORT_DAYS = 31

# Report dimensions and metrics (values verified against the v1 discovery document)
REPORT_DIMENSIONS = ["DATE", "APP", "AD_UNIT"]
REPORT_METRICS = [
    "AD_REQUESTS",
    "MATCHED_REQUESTS",
    "IMPRESSIONS",
    "CLICKS",
    "ESTIMATED_EARNINGS",
    "IMPRESSION_CTR",
    "IMPRESSION_RPM",
    "MATCH_RATE",
    "SHOW_RATE",
]
# microsValue metrics (money, expressed in currency units: 1_000_000 micros = 1 unit)
MONEY_METRICS = {"ESTIMATED_EARNINGS", "IMPRESSION_RPM"}
# doubleValue metrics (ratios from 0 to 1)
RATIO_METRICS = {"IMPRESSION_CTR", "MATCH_RATE", "SHOW_RATE"}

DEFAULT_CURRENCY = os.getenv("ADMOB_CURRENCY", "USD")


# ---------------------------------------------------------------------------
# Auth — AdMob requires user-based OAuth 2.0 (service accounts are NOT supported)
# ---------------------------------------------------------------------------
def get_admob_service():
    refresh_token = os.getenv("ADMOB_REFRESH_TOKEN")
    client_id = os.getenv("ADMOB_CLIENT_ID")
    client_secret = os.getenv("ADMOB_CLIENT_SECRET")

    # Optionally load client id/secret from the downloaded OAuth client JSON
    creds_file = os.getenv("ADMOB_CLIENT_CREDENTIALS")
    if creds_file and os.path.exists(creds_file):
        with open(creds_file) as f:
            config = json.load(f)
        oauth = config.get("installed") or config.get("web") or {}
        client_id = client_id or oauth.get("client_id")
        client_secret = client_secret or oauth.get("client_secret")

    missing = [
        name
        for name, value in (
            ("ADMOB_REFRESH_TOKEN", refresh_token),
            ("ADMOB_CLIENT_ID", client_id),
            ("ADMOB_CLIENT_SECRET", client_secret),
        )
        if not value
    ]
    if missing:
        raise ValueError(
            f"AdMob requires user-based OAuth. Missing env vars: {', '.join(missing)}. "
            "Create an OAuth client ID (Desktop app) in Cloud Console, invite your Google "
            "account in AdMob (Settings > Users), then run: "
            "python3 admob_oauth_setup.py --client-json <your_client_secret.json> "
            "and put the printed ADMOB_REFRESH_TOKEN into .env"
        )

    credentials = Credentials(
        token=None,
        refresh_token=refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=client_id,
        client_secret=client_secret,
    )
    return build("admob", "v1", credentials=credentials)


# ---------------------------------------------------------------------------
# API list helpers (with pagination)
# ---------------------------------------------------------------------------
def list_accounts(service):
    accounts = []
    page_token = None
    while True:
        req = service.accounts().list(pageToken=page_token) if page_token else service.accounts().list()
        resp = req.execute()
        accounts.extend(resp.get("account", []))
        page_token = resp.get("nextPageToken")
        if not page_token:
            break
        time.sleep(0.15)
    return accounts


def list_apps(service, pub_id):
    apps = []
    page_token = None
    parent = f"accounts/{pub_id}"
    while True:
        req = service.accounts().apps().list(parent=parent, pageToken=page_token) if page_token else service.accounts().apps().list(parent=parent)
        resp = req.execute()
        apps.extend(resp.get("apps", []))
        page_token = resp.get("nextPageToken")
        if not page_token:
            break
        time.sleep(0.15)
    return apps


def list_ad_units(service, pub_id):
    """Lists ALL ad units for the publisher account (adUnits are account-scoped,
    not app-scoped). Each AdUnit carries an appId to associate it to an app."""
    units = []
    page_token = None
    parent = f"accounts/{pub_id}"
    while True:
        req = service.accounts().adUnits().list(parent=parent, pageToken=page_token) if page_token else service.accounts().adUnits().list(parent=parent)
        resp = req.execute()
        units.extend(resp.get("adUnits", []))
        page_token = resp.get("nextPageToken")
        if not page_token:
            break
        time.sleep(0.15)
    return units


# ---------------------------------------------------------------------------
# Report generation & parsing
# ---------------------------------------------------------------------------
def generate_network_report(service, pub_id, start, end, currency, ad_unit_ids=None):
    report_spec = {
        "dateRange": {
            "startDate": {"year": start.year, "month": start.month, "day": start.day},
            "endDate": {"year": end.year, "month": end.month, "day": end.day},
        },
        "dimensions": REPORT_DIMENSIONS,
        "metrics": REPORT_METRICS,
        "localizationSettings": {"currencyCode": currency, "languageCode": "en-US"},
    }
    if ad_unit_ids:
        # Server-side filter (OR across the listed ad units) keeps the payload small
        report_spec["dimensionFilters"] = [
            {"dimension": "AD_UNIT", "matchesAny": {"values": ad_unit_ids}}
        ]
    body = {"reportSpec": report_spec}
    resp = service.accounts().networkReport().generate(
        parent=f"accounts/{pub_id}", body=body
    ).execute()
    time.sleep(0.15)
    return resp


def parse_report_response(resp):
    """
    The generate endpoint streams messages; the client may return either a list of
    {header|row|footer} messages or a single object with 'rows'. Handle both.
    """
    header, rows, footer = None, [], None
    if isinstance(resp, list):
        for msg in resp:
            if not isinstance(msg, dict):
                continue
            if "header" in msg:
                header = msg["header"]
            elif "row" in msg:
                rows.append(msg["row"])
            elif "footer" in msg:
                footer = msg["footer"]
    elif isinstance(resp, dict):
        header = resp.get("header")
        rows = resp.get("rows", [])
        footer = resp.get("footer")
    return header, rows, footer


def format_yyyymmdd(value):
    """'20260801' -> '2026-08-01'"""
    if not value:
        return None
    value = str(value)
    if len(value) == 8:
        return f"{value[0:4]}-{value[4:6]}-{value[6:8]}"
    return value


def app_key_from_report_value(value):
    """APP dimension value looks like 'ca-app-pub-8123...~1001342552'.
    Extract the trailing numeric app id ('1001342552')."""
    if not value:
        return value
    idx = str(value).rfind("~")
    return str(value)[idx + 1:] if idx >= 0 else str(value)


def app_key_from_app_resource(app):
    """App/AdUnit resource appId can be 'app-1318147953', 'ca-app-pub-PUB~1318147953'
    or '1318147953'. Normalize to the trailing numeric id so it matches the report's
    APP dimension value (which looks like 'ca-app-pub-PUB~1318147953')."""
    app_id = str(app.get("appId", ""))
    if app_id.startswith("app-"):
        return app_id[4:]
    idx = app_id.rfind("~")
    if idx >= 0:
        return app_id[idx + 1:]
    return app_id


def parse_report_rows(rows):
    records = []
    for row in rows:
        dv = row.get("dimensionValues", {})
        mv = row.get("metricValues", {})
        rec = {
            "date": format_yyyymmdd((dv.get("DATE") or {}).get("value")),
            "app_key": app_key_from_report_value((dv.get("APP") or {}).get("value")),
            "ad_unit_id": (dv.get("AD_UNIT") or {}).get("value"),
        }
        for metric in REPORT_METRICS:
            mval = mv.get(metric) or {}
            if "microsValue" in mval:
                rec[metric.lower()] = round(int(mval["microsValue"]) / 1_000_000.0, 6)
            elif "integerValue" in mval:
                rec[metric.lower()] = int(mval["integerValue"])
            elif "doubleValue" in mval:
                rec[metric.lower()] = float(mval["doubleValue"])
            else:
                rec[metric.lower()] = None
        records.append(rec)
    return records


# ---------------------------------------------------------------------------
# Data grouping / totals
# ---------------------------------------------------------------------------
def compute_totals(rows):
    impressions = sum(r.get("impressions") or 0 for r in rows)
    clicks = sum(r.get("clicks") or 0 for r in rows)
    earnings = sum(r.get("estimated_earnings") or 0 for r in rows)
    ad_requests = sum(r.get("ad_requests") or 0 for r in rows)
    matched = sum(r.get("matched_requests") or 0 for r in rows)
    return {
        "ad_requests": ad_requests,
        "matched_requests": matched,
        "impressions": impressions,
        "clicks": clicks,
        "estimated_earnings": round(earnings, 6),
        "ctr": round(clicks / impressions, 6) if impressions else 0.0,
        "ecpm": round(earnings / impressions * 1000.0, 6) if impressions else 0.0,
        "match_rate": round(matched / ad_requests, 6) if ad_requests else 0.0,
    }


def merge_app_totals(app_totals, unit_totals):
    for key in ("ad_requests", "matched_requests", "impressions", "clicks"):
        app_totals[key] += unit_totals[key]
    app_totals["estimated_earnings"] = round(
        app_totals["estimated_earnings"] + unit_totals["estimated_earnings"], 6
    )


def finalize_app_totals(app_totals):
    impressions = app_totals["impressions"]
    ad_requests = app_totals["ad_requests"]
    app_totals["ctr"] = round(app_totals["clicks"] / impressions, 6) if impressions else 0.0
    app_totals["ecpm"] = (
        round(app_totals["estimated_earnings"] / impressions * 1000.0, 6) if impressions else 0.0
    )
    app_totals["match_rate"] = (
        round(app_totals["matched_requests"] / ad_requests, 6) if ad_requests else 0.0
    )
    return app_totals


# ---------------------------------------------------------------------------
# LLM report generation
# ---------------------------------------------------------------------------
def call_gemini(prompt):
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in environment")
    import google.generativeai as genai

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite"))
    response = model.generate_content(prompt)
    return response.text


def call_local_llm(prompt):
    local_command = os.getenv("LOCAL_LLM_COMMAND")
    if not local_command:
        raise ValueError("LOCAL_LLM_COMMAND not found in environment")
    process = subprocess.Popen(
        local_command.split(),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    stdout, stderr = process.communicate(input=prompt)
    if process.returncode != 0:
        raise RuntimeError(f"Local LLM failed ({process.returncode}): {stderr}")
    return stdout


def format_app_data_for_prompt(pkg, app_data, period, currency):
    parts = []
    for unit_id, ud in sorted(app_data["ad_units"].items()):
        parts.append(f"### Ad unit {unit_id} ({ud['ad_format']})")
        rows = ud["rows"]
        if not rows:
            parts.append("No data for this period.")
        else:
            header = "| Date | Ad requests | Matched | Impressions | Clicks | CTR | Match rate | eCPM | Earnings |"
            sep = "|---|---|---|---|---|---|---|---|---|"
            lines = [header, sep]
            for r in rows:
                ctr = (r.get("clicks") or 0) / (r.get("impressions") or 0) if (r.get("impressions") or 0) else 0.0
                ecpm = (r.get("estimated_earnings") or 0) / (r.get("impressions") or 0) * 1000.0 if (r.get("impressions") or 0) else 0.0
                lines.append(
                    f"| {r.get('date') or '?'} | {r.get('ad_requests') or 0} | {r.get('matched_requests') or 0} "
                    f"| {r.get('impressions') or 0} | {r.get('clicks') or 0} | {ctr:.4f} | {r.get('match_rate') or 0:.4f} "
                    f"| {ecpm:.2f} | {r.get('estimated_earnings') or 0:.2f} |"
                )
            parts.append("\n".join(lines))
        t = ud["totals"]
        parts.append(
            f"*Totals: {t['ad_requests']} requests, {t['impressions']} impressions, {t['clicks']} clicks, "
            f"CTR {t['ctr']:.4f}, match rate {t['match_rate']:.4f}, eCPM {t['ecpm']:.2f}, "
            f"earnings {t['estimated_earnings']:.2f} {currency}*"
        )
        parts.append("")
    return "\n".join(parts)


def build_prompt(pkg, app_data, period, currency):
    formatted = format_app_data_for_prompt(pkg, app_data, period, currency)
    app_totals = app_data["totals"]
    return f"""You are a mobile monetization analyst for Google AdMob. Analyze the ad performance data for app '{pkg}' for the period {period['start']} to {period['end']}. All money values are in {currency}. CTR, match rate and show rate are ratios where 1.0 equals 100%.

App-level totals: {app_totals['ad_requests']} ad requests, {app_totals['impressions']} impressions, {app_totals['clicks']} clicks, CTR {app_totals['ctr']:.4f}, match rate {app_totals['match_rate']:.4f}, eCPM {app_totals['ecpm']:.2f} {currency}, total earnings {app_totals['estimated_earnings']:.2f} {currency}.

Data per ad unit:
{formatted}

Write a Markdown report that includes:
1. Overall monetization summary (total earnings, impressions, clicks, CTR, eCPM, match rate).
2. Day-to-day variations: notable spikes or drops and likely causes.
3. Per-ad-unit comparison: which ad units drive revenue, which underperform (low CTR, low eCPM, low match rate, low show rate, etc.).
4. Actionable recommendations for improving revenue and user experience.

Keep it concise but informative. Output in Markdown.
"""


def generate_reports_from_json(json_path, data, use_local):
    pub = data["publisher_id"]
    period = data["period"]
    currency = data.get("currency", DEFAULT_CURRENCY)
    for pkg, app_data in data["apps"].items():
        print(f"Generating AdMob report for {pkg}...")
        prompt = build_prompt(pkg, app_data, period, currency)
        report = call_local_llm(prompt) if use_local else call_gemini(prompt)
        if not report:
            raise ValueError(f"Failed to generate report for {pkg}")
        out_path = json_path.replace(".json", f"_{pkg.replace('.', '_')}.md")
        with open(out_path, "w") as f:
            f.write(report)
        print(f"Report saved to {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Fetch AdMob data and generate AI reports.")
    parser.add_argument("--days", type=int, default=7, help="Report period in days (max 31)")
    parser.add_argument("--account", type=str, default=None,
                        help="AdMob publisher ID (pub-...) override. Defaults to ADMOB_PUBLISHER_ID env or auto-discovery")
    parser.add_argument("--packages", type=str, default=None,
                        help="Comma-separated package names to filter (default: all linked apps)")
    parser.add_argument("--ad-units-config", type=str, default=None,
                        help="JSON file mapping app package -> [list of ad unit IDs]")
    parser.add_argument("--discover", action="store_true",
                        help="Auto-list apps and ad units from the AdMob API")
    parser.add_argument("--currency", type=str, default=DEFAULT_CURRENCY, help="Currency code (default: USD)")
    parser.add_argument("--fetch-only", action="store_true", help="Fetch data and save JSON, skip LLM report")
    parser.add_argument("--file", type=str, default=None, help="Generate LLM report from an existing admob_*.json file")
    parser.add_argument("--local", action="store_true", help="Use local LLM instead of Gemini")
    args = parser.parse_args()

    # ---- Mode: generate reports from an existing JSON file ----
    if args.file:
        with open(args.file) as f:
            data = json.load(f)
        generate_reports_from_json(args.file, data, args.local)
        return

    # ---- Mode: fetch ----
    service = get_admob_service()

    # Resolve publisher account
    pub_id = args.account or os.getenv("ADMOB_PUBLISHER_ID")
    if not pub_id:
        accounts = list_accounts(service)
        if not accounts:
            raise ValueError(
                "No AdMob accounts found for the OAuth-authenticated user. Make sure the "
                "Google account used in admob_oauth_setup.py has been invited in the AdMob "
                "console (Settings > Users) with access to at least one account, or set "
                "ADMOB_PUBLISHER_ID in .env."
            )
        if len(accounts) > 1:
            raise ValueError(
                f"Multiple AdMob accounts found: {[a.get('publisherId') for a in accounts]}. "
                "Set ADMOB_PUBLISHER_ID in .env to pick one."
            )
        pub_id = accounts[0]["publisherId"]
    print(f"Publisher account: {pub_id}")

    # List apps -> map numeric app id -> package name (linkedAppInfo.appStoreId)
    apps = list_apps(service, pub_id)
    pkg_by_app_key = {
        app_key_from_app_resource(a): (a.get("linkedAppInfo") or {}).get("appStoreId")
        for a in apps
    }
    print(f"Found {len(apps)} linked app(s) in AdMob: {sorted(set(p for p in pkg_by_app_key.values() if p))}")

    # List ad units for the whole account -> adUnitId -> {ad_format, app_key}
    units_map = {}
    for u in list_ad_units(service, pub_id):
        units_map[u["adUnitId"]] = {
            "ad_format": u.get("adFormat", "UNKNOWN"),
            "app_key": app_key_from_app_resource(u),
        }
    print(f"Found {len(units_map)} ad unit(s) across all apps.")

    # ---- Resolve target apps / ad units ----
    target_packages = None
    if args.packages:
        target_packages = {p.strip() for p in args.packages.split(",")}

    config = None
    target_ad_unit_ids = None
    if args.ad_units_config:
        with open(args.ad_units_config) as f:
            config = json.load(f)
        if not isinstance(config, dict):
            raise ValueError("Ad units config must be a JSON object mapping package -> [ad unit IDs]")
        target_ad_unit_ids = []
        for pkg, unit_ids in config.items():
            if not isinstance(unit_ids, list):
                raise ValueError(f"Config entry for '{pkg}' must be a list of ad unit IDs")
            for uid in unit_ids:
                if uid not in units_map:
                    available = sorted(u for u, meta in units_map.items() if meta["app_key"] in
                                       [k for k, p in pkg_by_app_key.items() if p == pkg])
                    raise ValueError(
                        f"Ad unit '{uid}' declared for '{pkg}' was not found in the AdMob account. "
                        f"Available ad units for '{pkg}': {available}"
                    )
            target_ad_unit_ids.extend(unit_ids)
    elif args.discover:
        target_ad_unit_ids = sorted(units_map.keys())

    # ---- Date range ----
    if args.days < 1:
        raise ValueError("--days must be >= 1")
    if args.days > MAX_REPORT_DAYS:
        raise ValueError(
            f"--days max is {MAX_REPORT_DAYS} for a single AdMob report request. "
            "Run in chunks for longer periods."
        )
    end = datetime.utcnow().date() - timedelta(days=1)
    start = end - timedelta(days=args.days - 1)

    # ---- Fetch report ----
    print(f"Fetching network report for {start} to {end}...")
    resp = generate_network_report(service, pub_id, start, end, args.currency, target_ad_unit_ids)
    _header, rows, _footer = parse_report_response(resp)
    records = parse_report_rows(rows)
    print(f"Report returned {len(records)} row(s).")

    # ---- Build per-app / per-ad-unit structure ----
    apps_out = {}
    # Pre-initialize entries so apps with zero data still appear
    if config:
        for pkg, unit_ids in config.items():
            app_key = next((k for k, p in pkg_by_app_key.items() if p == pkg), None)
            apps_out[pkg] = {"app_key": app_key, "ad_units": {}}
            for uid in unit_ids:
                apps_out[pkg]["ad_units"][uid] = {
                    "ad_format": units_map.get(uid, {}).get("ad_format", "UNKNOWN"),
                    "rows": [],
                }
    elif target_packages is None:
        for app_key, pkg in pkg_by_app_key.items():
            pkg = pkg or f"unlinked-{app_key}"
            if target_packages is not None and pkg not in target_packages:
                continue
            apps_out[pkg] = {"app_key": app_key, "ad_units": {}}
            for uid, meta in units_map.items():
                if meta["app_key"] == app_key:
                    apps_out[pkg]["ad_units"][uid] = {"ad_format": meta["ad_format"], "rows": []}

    # Merge report records into the structure
    matched_records = 0
    for rec in records:
        pkg = pkg_by_app_key.get(rec["app_key"])
        if not pkg:
            continue
        if target_packages is not None and pkg not in target_packages:
            continue
        matched_records += 1
        app_entry = apps_out.setdefault(pkg, {"app_key": rec["app_key"], "ad_units": {}})
        unit_entry = app_entry["ad_units"].setdefault(
            rec["ad_unit_id"],
            {
                "ad_format": units_map.get(rec["ad_unit_id"], {}).get("ad_format", "UNKNOWN"),
                "rows": [],
            },
        )
        unit_entry["rows"].append(rec)

    if records:
        sample = records[0]
        print(f"Sample row: date={sample.get('date')} app_key={sample.get('app_key')} "
              f"ad_unit={sample.get('ad_unit_id')} impressions={sample.get('impressions')} "
              f"earnings={sample.get('estimated_earnings')}")
        if matched_records == 0:
            raise ValueError(
                "Report returned rows but none matched any linked app. This usually means "
                "the app id format in report rows differs from the app list. "
                f"Report app keys sample: {sorted({r['app_key'] for r in records[:10]})}; "
                f"Known app keys: {sorted(pkg_by_app_key.keys())}"
            )
        if matched_records < len(records):
            print(f"  Note: {len(records) - matched_records} of {len(records)} row(s) did not match "
                  f"a linked app and were skipped.")

    # Compute totals
    for pkg, app_entry in apps_out.items():
        app_totals = {"ad_requests": 0, "matched_requests": 0, "impressions": 0,
                      "clicks": 0, "estimated_earnings": 0.0}
        for unit_entry in app_entry["ad_units"].values():
            unit_entry["rows"].sort(key=lambda r: r.get("date") or "")
            unit_entry["totals"] = compute_totals(unit_entry["rows"])
            merge_app_totals(app_totals, unit_entry["totals"])
        app_entry["totals"] = finalize_app_totals(app_totals)

    # ---- Save JSON ----
    data_dir = "data"
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    json_path = os.path.join(data_dir, f"admob_{timestamp}.json")
    out = {
        "publisher_id": pub_id,
        "period": {"start": start.isoformat(), "end": end.isoformat()},
        "currency": args.currency,
        "apps": apps_out,
    }
    with open(json_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"Data saved to {json_path}")

    # ---- LLM report ----
    if not args.fetch_only:
        if not apps_out:
            raise ValueError("No app data to report on. Check --packages / --ad-units-config / --discover.")
        generate_reports_from_json(json_path, out, args.local)
    else:
        print("--fetch-only set: skipping LLM report.")


if __name__ == "__main__":
    main()
